### PR TITLE
Copyright claim for Michael Carlberg

### PR DESCRIPTION
**Pull request by patrick96**
@jaagr needs to approve this before merging, because it is his copyright claim

### CODE REVIEW

**Comment by NBonaparte** [comment]
Why is the delete reader fix here? I thought we already merged it.

**Comment by patrick96** [comment]
I don't know, somehow got into the commit history when I rebased against master. Gonna try to do a force push

**Review by jaagr — COMMENTED** [review]
Wouldn't it make more sense to put "Modified work Copyright 2018, Contributors"? Because I am not the only one who have contributed to the code after forking the repository.

**Comment by patrick96** [comment]
I think the copyright notice actually needs to have a name on it and I don't think adding each contributor separately is a good idea. And since you are the owner of this fork, your name should probably appear there.

**Comment by NBonaparte** [comment]
We could do "Modified work Copyright 2018, Michael Carlberg and contributors" as well (contributors is just "contributors", see the [i3 license](https://github.com/i3/i3/blob/master/LICENSE) as an example).

**Comment by patrick96** [comment]
Yeah, we could do that. I'll push the changes here and over at xpp during the day.

**Review by jaagr — APPROVED** [review]

**Pull request merged**
